#:schema node_modules/wrangler/config-schema.json
name = "workersaibskybot"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[ai]
binding = "AI"

[triggers]
# Schedule cron triggers:
crons = [ "*/30 * * * *" ] # every 30 minutes